### PR TITLE
Network wide settings

### PR DESCRIPTION
**Pull request by thomaslhotta**
I implemented the functionality as discussed in #69. It is not ready for merging as not everything has been tested yet, but I created this pull request for discussion anyway.

I have made the following changes:
- Added a settings page to the network admin
- Made some small changes to the CSS to make it work in the network admin. There may still be some glitches to fix
- Added an option to allow overriding of the settings for individual blogs
- If the plugin is network activated the settings pages for API keys are only available in the network admin. As far as I am concerned the only use case for individual API keys for each blog would be a large site like wordpress.com where blogs have their own domains. I don't see this plugin being used for such large operations quite yet :)
- Added some security checks to deal with overriding settings
- Added unit tests for the new functions

Some open discussion points/todos are:
- Coding standards? 
- Implementation details
- More unit tests
- Maybe some more extensive refactoring to clean up the settings page code

Any thoughts?

### CODE REVIEW

**Comment by bcole808** [comment]
Thanks! At a glance, this looks quite good. I will see if I can spend some more time testing it out in the next couple of days.

**Comment by bcole808** [comment]
Last thoughts for now:

## Network settings page

It does make sense that the API settings / Google Analytics settings should only be network wide. 

But maybe we should add something to the UI so that people using the plugin understand how it works and that if they network-activate the plugin then those settings only show up in the network page. But if they individually activate the plugin on each blog (instead of using network-activation) then they can still change those items for each individual blog. 

## General

Again, overall this looks good and I'm really happy to have you helping with this feature! 

I can either merge this now (to the `issue-69-multisite-settings` branch) and we can keep working with a new pull request, or I can leave it open if you want to add more commits first. Once it's merged I'll see if I can write a few tests and maybe do a tiny bit of cleanup.

**Comment by thomaslhotta** [comment]
The ! on line 123 was just debug code that I forgot to remove, thanks for pointing that out.

I'm not sure about what the best approach is concerning merging. I have never had the honour of being 'pull requested' :) . As I will be developing with my own fork anyway I guess it is up to what is more convenient for you.

I agree that a function for checking settings overriding would be more readable. While we are at this I think it would be a good idea to move all the options handling to a separate class to prevent cluttering the main class. This would also remove the dependency of the `socialMetricsSettings` on the `SocialMetricsTracker` class and unit testing would become easier.

**Comment by bcole808** [comment]
I'll merge now so that I can also do a little bit of code cleanup (since it's merging to the branch "issue-69-multisite-settings" instead of "development" I think it's okay that it's still a work in progress). 

Moving the options handling to a separate class could be good. It is definitely referenced in a lot of places though, so it might result in a pretty massive find/replace task to update all of the spots where options are referenced through the entire plugin. 

Up to you if you want to tackle that now, or we could wrap up the network settings feature (and get it merged/deployed) and then start a new branch to do that cleanup/organization task.  Or if it makes more sense to do it now, go for it!

**Pull request merged**
