### PR TITLE
Update to Facebook Graph API v2.9

### LINKED ISSUE #85: Facebook Graph API needs update
Facebook is retiring v2.3 of the Graph API July 10 2017. From what we can tell, the Graph API updater is going to stop working after this date.

### PR DESCRIPTION
**Pull request by kristianj**
fixes #85

### CODE REVIEW

**Comment by bcole808** [comment]
Thanks for putting together this pull request! When you tested this, were the share numbers returned by this new API version the same share numbers that were being returned by the old version?

In other words, were you able to test that the share count for the URLs is the same when changing versions of the FB API?

**Comment by kristianj** [comment]
Yes, for the posts I tested this on I got the same share counts as before.

Looked at the documentation for the new API version again now and realized the comment_plugin_count probably also was included in the old share count. Have included this number as well now.

**Comment by bcole808** [comment]
Thanks! I'll work on getting this merged and deployed soon.

**Comment by bcole808** [comment]
@kristianj This is now deployed as version 1.6.8 - Thanks for helping to get this done! I just don't have enough time to actively work on this plugin right now so I appreciate that there are others who can help push the plugin forward to keep up with the changing APIs.

**Pull request merged**
