### PR TITLE
Adding ability to custom sort/filter social metrics dashboard query

### PR DESCRIPTION
**Pull request by bamadesigner**
Just wanted to show you some tweaks I made to the plugin today so I could add in my own sorting and filtering. The 'smt_restrict_manage_social_metrics_dashboard' action is the important part in order to add the HTML for filtering and then I simplifed your query in prepare_items() and moved your different sorting mechanisms to a 'pre_get_posts' hook to clean things up. I also added a filter at the end of the 'pre_get_posts' hook so I could filter the query even further with my own tweaks. Adding a 'smt_query' variable to the filter allows me to signify when a social media tracker query is happening, as opposed to any other query, for conditional sorting/filtering purposes. My name is all over the place because that's my method of discovering when I've altered someone else's code. :)

### CODE REVIEW

**Comment by bcole808** [comment]
What custom sorting and filtering options did you add in for your site? If they would benefit other plugin users I would love to consider adding the additional sorting options, unless they are specific to your site. I know we discussed adding an "items per page" option, were there any others?

**Comment by bamadesigner** [comment]
@jonathantneal After the part about "My name is all over the place...", I should have included "So feel free to delete all that." :) I was just trying to say you will not offend me by taking it out. I probably should have deleted it before I committed. I'm pseudo new to forking/contributing other's people's repos. I'll get the hang of it eventually. ;) And yes, comments are sweet treats for other developers.

@bcole808 At this point, the only custom filters I've setup are super custom for my site. Basically, I designed a news portal for our college that automatically pulls in stories from designated news feeds and external news sources and saves identifying info (title, permalink, source, etc) in our system so we can "tag" those stories and share them throughout our network. But we also have original news stories so I wanted to be able to filter the social metrics to only show "original" news posts. If you're looking for additional sorting options that could be beneficial, you might consider adding the ability to sort by taxonomies that are assigned to the post type.

**Comment by bcole808** [comment]
Thanks for the clarification, I will add in many of these changes and new action hooks later this week. I definitely want to make this plugin extensible for custom use cases.  

Thanks again for contributing! I'm excited to finally be able to collaborate with others to improve this plugin. For the future, it is helpful for reviewing pull requests if git commits are consolidated so that one feature corresponds to one commit. That makes it easier to review and see which changes corresponded to which features.

**Comment by bcole808** [comment]
@bamadesigner - I merged these changes; the way that you handled query sorting with a function was much better than how it was being done before, thanks! I moved that function into the _SocialMetricsTable_ class so that it doesn't run anywhere else in WordPress, so the 'smt_query' parameter is no longer necessary. 

I also re-named your action hook **smt_restrict_manage_social_metrics_dashboard** to **smt_dashboard_query_options** which more closely matches the query filter which it is associated with - you'll need to update your custom code with this new action hook name, but I think that's the only change I made which affects your custom code. 

Thanks again for contributing, and please send more pull requests in the future if you find the time to work on any of the features on the issue list. I want to get to them all but it's sometimes hard for me to find time to do them.

**Comment by bamadesigner** [comment]
Awesome. Will do!

**Pull request merged**
